nama = input("Nama                  : ")
nim = input("NIM                   : ")
kelas = int(input("Kelas Paralel         : "))
ttl = input("Tempat/Tanggal Lahir  : ")
alamat = input("Alamat                : ")
hobi = input("Hobby                 : ")
no_hp = input("No. HP                : ")

print("\nNama                  : ", nama)
print("NIM                   : ", nim)
print("Kelas Paralel         : ", kelas)
print("Tempat/Tanggal Lahir  : ", ttl)
print("Alamat                : ", alamat)
print("Hobby                 : ", hobi)
print("No. HP                : ", no_hp)